# Generated by Django 5.1 on 2024-08-22 17:36

import apps_manager.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_manager', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='apk_file_path',
            field=models.FileField(upload_to='apk_files/', validators=[apps_manager.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='app',
            name='first_screen_screenshot_path',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='second_screen_screenshot_path',
            field=models.ImageField(blank=True, null=True, upload_to='screenshots/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='ui_hierarchy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app',
            name='video_recording_path',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
